package com.forecast.app.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.forecast.app.db.DailyForecast;

import com.forecast.app.db.DailyForecastDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyForecastDaoConfig;

    private final DailyForecastDao dailyForecastDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyForecastDaoConfig = daoConfigMap.get(DailyForecastDao.class).clone();
        dailyForecastDaoConfig.initIdentityScope(type);

        dailyForecastDao = new DailyForecastDao(dailyForecastDaoConfig, this);

        registerDao(DailyForecast.class, dailyForecastDao);
    }
    
    public void clear() {
        dailyForecastDaoConfig.getIdentityScope().clear();
    }

    public DailyForecastDao getDailyForecastDao() {
        return dailyForecastDao;
    }

}
